
const menuButton=document.querySelector('.menu-button');const navLinks=document.querySelector('.nav-links');if(menuButton&&navLinks){menuButton.addEventListener('click',()=>{const open=navLinks.classList.toggle('open');menuButton.setAttribute('aria-expanded',String(open))});navLinks.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{navLinks.classList.remove('open');menuButton.setAttribute('aria-expanded','false')}))}
const header=document.querySelector('.site-header');addEventListener('scroll',()=>header&&header.classList.toggle('scrolled',scrollY>20),{passive:true});
const revealObs=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');revealObs.unobserve(e.target)}}),{threshold:.12});document.querySelectorAll('.reveal').forEach(el=>revealObs.observe(el));
const fmt=(n,el)=>(el.dataset.prefix||'')+Math.round(n)+(el.dataset.suffix||'');const countObs=new IntersectionObserver(entries=>entries.forEach(e=>{if(!e.isIntersecting)return;const el=e.target,target=+el.dataset.count,start=performance.now(),dur=1100;const tick=t=>{const p=Math.min(1,(t-start)/dur),ease=1-Math.pow(1-p,3);el.textContent=fmt(target*ease,el);if(p<1)requestAnimationFrame(tick)};requestAnimationFrame(tick);countObs.unobserve(el)}),{threshold:.55});document.querySelectorAll('[data-count]').forEach(el=>countObs.observe(el));
const glow=document.querySelector('.cursor-glow');if(glow&&matchMedia('(pointer:fine)').matches){addEventListener('pointermove',e=>{glow.style.transform=`translate(${e.clientX-210}px,${e.clientY-210}px)`},{passive:true})}
document.querySelectorAll('.tilt').forEach(card=>{card.addEventListener('pointermove',e=>{if(!matchMedia('(pointer:fine)').matches)return;const r=card.getBoundingClientRect(),x=(e.clientX-r.left)/r.width,y=(e.clientY-r.top)/r.height;card.style.setProperty('--mx',`${x*100}%`);card.style.setProperty('--my',`${y*100}%`);card.style.transform=`perspective(1100px) rotateX(${(0.5-y)*2.2}deg) rotateY(${(x-0.5)*2.2}deg) translateY(-3px)`});card.addEventListener('pointerleave',()=>card.style.transform='')});
const steps=[...document.querySelectorAll('.process-step')],progress=document.querySelector('.process-progress span');if(steps.length){const stepObs=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){steps.forEach(s=>s.classList.remove('in-view'));e.target.classList.add('in-view');if(progress)progress.style.width=`${(+e.target.dataset.step/steps.length)*100}%`}}),{rootMargin:'-35% 0px -45% 0px',threshold:0});steps.forEach(s=>stepObs.observe(s))}
const caseSections=[...document.querySelectorAll('.case-body section[id]')],caseLinks=[...document.querySelectorAll('.case-nav a')];if(caseSections.length&&caseLinks.length){const navObs=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){caseLinks.forEach(a=>a.classList.toggle('active',a.getAttribute('href')==='#'+e.target.id))}}),{rootMargin:'-30% 0px -60% 0px'});caseSections.forEach(s=>navObs.observe(s))}
const year=document.querySelector('[data-year]');if(year)year.textContent=new Date().getFullYear();
